# Generated by Django 5.2 on 2025-05-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('admin', 'Admin'), ('registrar', 'Registrar'), ('none', 'None'), ('system_admin', 'System Admin')], default='none', max_length=20),
        ),
    ]
