# Generated by Django 5.2 on 2025-06-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_patient_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("personal", "Personal"),
                    ("clinic", "Clinic"),
                    ("group", "Group"),
                ],
                default="personal",
                max_length=20,
            ),
        ),
    ]
