# Generated by Django 5.2 on 2025-06-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registered',
            field=models.BooleanField(default=False, help_text='Indicates if the user has completed registration'),
        ),
    ]
