# Generated by Django 4.2 on 2025-06-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_patient_medical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Whether user is currently online'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time user was active', null=True),
        ),
    ]
