# Generated by Django 4.2 on 2025-06-13 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_chat_models'),
        ('users', '0018_chat_models'),
    ]

    operations = [
    ]
