# Generated by Django 4.2 on 2025-07-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_onlineuser_alter_typingindicator_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sms_consent',
            field=models.BooleanField(default=False, help_text='User has consented to receive SMS notifications'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_consent_date',
            field=models.DateTimeField(blank=True, help_text='When the user gave SMS consent', null=True),
        ),
    ]
