# Generated by Django 4.2 on 2025-06-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_onlineuser_alter_typingindicator_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sms_consent',
            field=models.BooleanField(default=False, help_text='User consent for SMS notifications'),
        ),
    ]
