# Generated by Django 4.2 on 2025-06-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_add_sms_consent_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login_completed',
            field=models.BooleanField(default=False, help_text='Whether user has completed first login password change'),
        ),
    ]
