# Generated by Django 4.2 on 2025-08-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_chat_models_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason provided for account cancellation', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cancellation_type',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled')], help_text='Type of cancellation', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the account was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='scheduled_cancellation_date',
            field=models.DateField(blank=True, help_text='Scheduled date for account cancellation', null=True),
        ),
    ]
