# Generated by Django 4.2 on 2025-08-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_add_account_cancellation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sms_opt_out',
            field=models.BooleanField(default=False, help_text='User has opted out of SMS notifications'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_opt_out_date',
            field=models.DateTimeField(blank=True, help_text='When the user opted out of SMS', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_opt_out_method',
            field=models.CharField(blank=True, choices=[('STOP', 'STOP keyword'), ('UNSUBSCRIBE', 'UNSUBSCRIBE keyword'), ('MANUAL', 'Manual opt-out'), ('ADMIN', 'Admin action')], help_text='How the user opted out of SMS', max_length=20, null=True),
        ),
    ]
