# Generated by Django 4.2 on 2026-09-26 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_customuser_add_nurse_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRightOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("right_code", models.CharField(max_length=64)),
                (
                    "is_granted",
                    models.BooleanField(
                        help_text="True grants this right beyond the user's role default; False revokes it."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which admin/system_admin last changed this override",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="right_overrides_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="right_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Right Override",
                "verbose_name_plural": "User Right Overrides",
                "unique_together": {("user", "right_code")},
            },
        ),
    ]
