# Generated by Django 4.2 on 2026-09-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_userrightoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='staffing_messaging_enabled',
            field=models.BooleanField(default=True, help_text="Master on/off switch for this organization's automatic Staffing SMS/email messaging -- shift reminders and understaffing coverage alerts. Turning this off stops the hourly automated jobs from sending anything for this organization; it does not affect ad-hoc messages an admin sends manually from the Roster tab."),
        ),
    ]
