# Generated by Django 4.2 on 2026-10-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_organization_address_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="lab_interface_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Paid add-on: electronic lab connection (Quest, Labcorp, ...). Lab results can always be entered by hand or scanned; this switch only unlocks the automatic electronic interface for this organization. Only a system admin can change it.",
            ),
        ),
    ]
