# Generated by Django 4.2 on 2026-10-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_organization_lab_interface_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="npi",
            field=models.CharField(
                blank=True,
                help_text="National Provider Identifier (providers only)",
                max_length=10,
            ),
        ),
    ]
