# Generated by Django 4.2 on 2026-10-06 02:57

from django.db import migrations, models


def backfill_care_setting(apps, schema_editor):
    """Existing visits: emergency stays Emergency, direct admissions are Acute, everything else Ambulatory."""
    Registration = apps.get_model("users", "Registration")
    Registration.objects.filter(care_setting="", admission_type="emergency").update(care_setting="emergency")
    Registration.objects.filter(care_setting="", admission_type="direct").update(care_setting="acute")
    Registration.objects.filter(care_setting="").update(care_setting="ambulatory")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_lab_orders_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="care_setting",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ambulatory", "Ambulatory Care"),
                    ("emergency", "Emergency Care"),
                    ("acute", "Acute Care"),
                ],
                max_length=12,
            ),
        ),
        migrations.RunPython(backfill_care_setting, migrations.RunPython.noop),
    ]
