# Generated by Django 4.2 on 2026-10-09 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0041_remove_old_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="removed_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
