# Generated by Django 4.2 on 2025-08-24 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_add_account_cancellation_fields'),
        ('communicator', '0002_messagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization associated with this message, used when user is None or to scope logs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='users.organization'),
        ),
    ]
