# Generated by Django 4.2 on 2025-08-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicator', '0003_messagelog_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='message_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('webhook', 'SMS Webhook')], max_length=10),
        ),
    ]
