#!/bin/bash

echo "🚀 FORCE Azure Container App Update with Digest - Aug 11 2025"
echo "=============================================================="
echo ""

# Get current commit hash
COMMIT_HASH=$(git rev-parse HEAD)
SHORT_HASH=$(git rev-parse --short HEAD)
echo "📋 Current commit: $COMMIT_HASH"
echo "📋 Short hash: $SHORT_HASH"
echo ""

echo "🔧 OPTION 1: Update with specific commit tag + force pull"
echo "--------------------------------------------------------"
echo "az containerapp update \\"
echo "  --name poehr-scheduling \\"
echo "  --resource-group poehr-scheduling-rg \\"
echo "  --image poehrschedulingacr.azurecr.io/poehr-scheduling:$COMMIT_HASH \\"
echo "  --revision-suffix forcepull$(date +%s) \\"
echo "  --min-replicas 0 \\"
echo "  --max-replicas 1"
echo ""
echo "# Then scale back up to force new pods"
echo "az containerapp update \\"
echo "  --name poehr-scheduling \\"
echo "  --resource-group poehr-scheduling-rg \\"
echo "  --min-replicas 1 \\"
echo "  --max-replicas 1"
echo ""

echo "🔧 OPTION 2: Get image digest and use it (most reliable)"
echo "--------------------------------------------------------"
echo "# First, get the digest of our latest image"
echo "DIGEST=\$(az acr repository show-manifests \\"
echo "  --name poehrschedulingacr \\"
echo "  --repository poehr-scheduling \\"
echo "  --query '[?tags[0]==\`$COMMIT_HASH\`].digest' \\"
echo "  --output tsv)"
echo ""
echo "# Update using digest (this forces a new pull)"
echo "az containerapp update \\"
echo "  --name poehr-scheduling \\"
echo "  --resource-group poehr-scheduling-rg \\"
echo "  --image poehrschedulingacr.azurecr.io/poehr-scheduling@\$DIGEST \\"
echo "  --revision-suffix digest$(date +%s)"
echo ""

echo "🔧 OPTION 3: Nuclear option - Delete and recreate revision"
echo "----------------------------------------------------------"
echo "# Get current revision"
echo "CURRENT_REV=\$(az containerapp revision list \\"
echo "  --name poehr-scheduling \\"
echo "  --resource-group poehr-scheduling-rg \\"
echo "  --query '[0].name' -o tsv)"
echo ""
echo "# Deactivate current revision"
echo "az containerapp revision deactivate \\"
echo "  --name poehr-scheduling \\"
echo "  --resource-group poehr-scheduling-rg \\"
echo "  --revision \$CURRENT_REV"
echo ""
echo "# Create new revision with latest image"
echo "az containerapp update \\"
echo "  --name poehr-scheduling \\"
echo "  --resource-group poehr-scheduling-rg \\"
echo "  --image poehrschedulingacr.azurecr.io/poehr-scheduling:latest \\"
echo "  --revision-suffix fresh$(date +%s)"
echo ""

echo "🔧 OPTION 4: Quick verification commands"
echo "----------------------------------------"
echo "# Check what image is currently running"
echo "az containerapp revision list \\"
echo "  --name poehr-scheduling \\"
echo "  --resource-group poehr-scheduling-rg \\"
echo "  --query '[0].{name:name,image:properties.template.containers[0].image,active:properties.active}' \\"
echo "  --output table"
echo ""
echo "# Check frontend file being served"
echo "curl -s 'https://poehr-scheduling.bluedune-dee8c412.centralus.azurecontainerapps.io/' | grep -o 'main\.[a-f0-9]*\.js'"
echo ""
echo "# Test for deployment banner"
echo "curl -s 'https://poehr-scheduling.bluedune-dee8c412.centralus.azurecontainerapps.io/static/js/main.e4f41ea3.js' | grep -c 'DEPLOYMENT TEST ACTIVE' || echo 'Banner not found'"
echo ""

echo "✅ TARGET: main.e4f41ea3.js with 'DEPLOYMENT TEST ACTIVE - AUG 11 2025'"
echo "❌ CURRENT: main.742304e6.js (old version)"
echo ""
echo "🎯 After successful update, you should see:"
echo "   - 🚨🚨🚨 DEPLOYMENT TEST ACTIVE - AUG 11 2025 🚨🚨🚨"
echo "   - Red banner with yellow border"
echo "   - main.e4f41ea3.js file being served"
