#!/bin/bash

echo "🔧 Manual Azure Container App Update"
echo "====================================="
echo ""
echo "Since GitHub is blocking the push due to secrets in git history,"
echo "here's how to manually update your Azure deployment:"
echo ""
echo "1. Build and push new image:"
echo "   az acr build --registry poehrschedulingacr --image poehr-scheduling:$(date +%Y%m%d-%H%M%S) ."
echo ""
echo "2. Update container app:"
echo "   az containerapp update \\"
echo "     --name poehr-scheduling \\"
echo "     --resource-group poehr-scheduling-rg \\"
echo "     --image poehrschedulingacr.azurecr.io/poehr-scheduling:$(date +%Y%m%d-%H%M%S)"
echo ""
echo "3. Monitor deployment:"
echo "   az containerapp logs show --name poehr-scheduling --resource-group poehr-scheduling-rg --follow"
echo ""
echo "📋 The key changes made:"
echo "- ✅ Removed Redis cache dependency"
echo "- ✅ Removed Redis channels dependency" 
echo "- ✅ Fixed database connection issues"
echo "- ✅ Admin user exists with credentials: jsswp2004/krat25Miko!"
echo ""
echo "🎯 After deployment, test login at:"
echo "   https://poehr-scheduling.bluedune-dee8c412.centralus.azurecontainerapps.io/"
