--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Debian 15.13-1.pgdg120+1)
-- Dumped by pg_dump version 15.13 (Debian 15.13-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: appointments_appointment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointments_appointment (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    appointment_datetime timestamp with time zone NOT NULL,
    duration_minutes integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    patient_id bigint NOT NULL,
    recurrence character varying(10) NOT NULL,
    provider_id bigint,
    organization_id bigint,
    status character varying(20) NOT NULL,
    recurrence_end_date date,
    arrived boolean NOT NULL,
    no_show boolean NOT NULL,
    CONSTRAINT appointments_appointment_duration_minutes_check CHECK ((duration_minutes >= 0))
);


ALTER TABLE public.appointments_appointment OWNER TO postgres;

--
-- Name: appointments_appointment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.appointments_appointment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_appointment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments_autoemail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointments_autoemail (
    id bigint NOT NULL,
    auto_message_frequency character varying(20) NOT NULL,
    auto_message_day_of_week integer NOT NULL,
    auto_message_start_date date,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    organization_id bigint
);


ALTER TABLE public.appointments_autoemail OWNER TO postgres;

--
-- Name: appointments_autoemail_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.appointments_autoemail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_autoemail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments_availability; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointments_availability (
    id bigint NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    is_blocked boolean NOT NULL,
    recurrence character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    doctor_id bigint NOT NULL,
    recurrence_end_date date,
    organization_id bigint,
    block_type character varying(32)
);


ALTER TABLE public.appointments_availability OWNER TO postgres;

--
-- Name: appointments_availability_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.appointments_availability ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_availability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments_clinicevent; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointments_clinicevent (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    is_active boolean NOT NULL
);


ALTER TABLE public.appointments_clinicevent OWNER TO postgres;

--
-- Name: appointments_clinicevent_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.appointments_clinicevent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_clinicevent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments_environmentsetting; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointments_environmentsetting (
    id bigint NOT NULL,
    blocked_days integer[] NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.appointments_environmentsetting OWNER TO postgres;

--
-- Name: appointments_environmentsetting_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.appointments_environmentsetting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_environmentsetting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments_holiday; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointments_holiday (
    id bigint NOT NULL,
    name character varying(64) NOT NULL,
    date date NOT NULL,
    is_recognized boolean NOT NULL,
    suppressed boolean NOT NULL
);


ALTER TABLE public.appointments_holiday OWNER TO postgres;

--
-- Name: appointments_holiday_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.appointments_holiday ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_holiday_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: communicator_contact; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.communicator_contact (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    uploaded_by_id bigint NOT NULL
);


ALTER TABLE public.communicator_contact OWNER TO postgres;

--
-- Name: communicator_contact_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.communicator_contact ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.communicator_contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: communicator_messagelog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.communicator_messagelog (
    id bigint NOT NULL,
    recipient character varying(255) NOT NULL,
    subject character varying(255) NOT NULL,
    body text NOT NULL,
    message_type character varying(10) NOT NULL,
    status character varying(20) NOT NULL,
    provider_id character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.communicator_messagelog OWNER TO postgres;

--
-- Name: communicator_messagelog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.communicator_messagelog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.communicator_messagelog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_cron_cronjoblock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_cron_cronjoblock (
    id integer NOT NULL,
    job_name character varying(200) NOT NULL,
    locked boolean NOT NULL
);


ALTER TABLE public.django_cron_cronjoblock OWNER TO postgres;

--
-- Name: django_cron_cronjoblock_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_cron_cronjoblock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_cron_cronjoblock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_cron_cronjoblog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_cron_cronjoblog (
    id integer NOT NULL,
    code character varying(64) NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    is_success boolean NOT NULL,
    message text NOT NULL,
    ran_at_time time without time zone
);


ALTER TABLE public.django_cron_cronjoblog OWNER TO postgres;

--
-- Name: django_cron_cronjoblog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_cron_cronjoblog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_cron_cronjoblog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_rest_passwordreset_resetpasswordtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_rest_passwordreset_resetpasswordtoken (
    created_at timestamp with time zone NOT NULL,
    key character varying(64) NOT NULL,
    ip_address inet,
    user_agent character varying(512) NOT NULL,
    user_id bigint NOT NULL,
    id integer NOT NULL
);


ALTER TABLE public.django_rest_passwordreset_resetpasswordtoken OWNER TO postgres;

--
-- Name: django_rest_passwordreset_resetpasswordtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_rest_passwordreset_resetpasswordtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_rest_passwordreset_resetpasswordtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: users_chatmessage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_chatmessage (
    id bigint NOT NULL,
    message text NOT NULL,
    message_type character varying(20) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    is_read boolean NOT NULL,
    recipient_id bigint,
    room_id bigint NOT NULL,
    sender_id bigint NOT NULL
);


ALTER TABLE public.users_chatmessage OWNER TO postgres;

--
-- Name: users_chatmessage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_chatmessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_chatmessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_chatroom; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_chatroom (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    room_type character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.users_chatroom OWNER TO postgres;

--
-- Name: users_chatroom_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_chatroom ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_chatroom_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_chatroom_participants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_chatroom_participants (
    id bigint NOT NULL,
    chatroom_id bigint NOT NULL,
    customuser_id bigint NOT NULL
);


ALTER TABLE public.users_chatroom_participants OWNER TO postgres;

--
-- Name: users_chatroom_participants_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_chatroom_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_chatroom_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_customuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(20) NOT NULL,
    provider_id bigint,
    profile_picture character varying(100),
    phone_number character varying(20),
    organization_id bigint,
    organization_type character varying(20) NOT NULL,
    registered boolean NOT NULL,
    stripe_customer_id character varying(255),
    stripe_subscription_id character varying(255),
    subscription_status character varying(50) NOT NULL,
    subscription_tier character varying(50) NOT NULL,
    trial_end_date timestamp with time zone,
    trial_start_date timestamp with time zone,
    is_online boolean NOT NULL,
    last_seen timestamp with time zone
);


ALTER TABLE public.users_customuser OWNER TO postgres;

--
-- Name: users_customuser_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_customuser_groups OWNER TO postgres;

--
-- Name: users_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_customuser_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_customuser_user_permissions OWNER TO postgres;

--
-- Name: users_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_onlineuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_onlineuser (
    user_id bigint NOT NULL,
    is_online boolean NOT NULL,
    last_seen timestamp with time zone NOT NULL
);


ALTER TABLE public.users_onlineuser OWNER TO postgres;

--
-- Name: users_organization; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_organization (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    logo character varying(100),
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.users_organization OWNER TO postgres;

--
-- Name: users_organization_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_organization ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_organization_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_patient; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_patient (
    id bigint NOT NULL,
    date_of_birth date,
    phone_number character varying(15) NOT NULL,
    address character varying(255) NOT NULL,
    medical_history text,
    user_id bigint NOT NULL,
    organization_id bigint
);


ALTER TABLE public.users_patient OWNER TO postgres;

--
-- Name: users_patient_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_patient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_patient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_typingindicator; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_typingindicator (
    id bigint NOT NULL,
    is_typing boolean NOT NULL,
    last_typing_time timestamp with time zone NOT NULL,
    room_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.users_typingindicator OWNER TO postgres;

--
-- Name: users_typingindicator_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_typingindicator ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_typingindicator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: appointments_appointment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.appointments_appointment (id, title, description, appointment_datetime, duration_minutes, created_at, updated_at, patient_id, recurrence, provider_id, organization_id, status, recurrence_end_date, arrived, no_show) FROM stdin;
\.


--
-- Data for Name: appointments_autoemail; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.appointments_autoemail (id, auto_message_frequency, auto_message_day_of_week, auto_message_start_date, is_active, created_at, updated_at, organization_id) FROM stdin;
\.


--
-- Data for Name: appointments_availability; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.appointments_availability (id, start_time, end_time, is_blocked, recurrence, created_at, doctor_id, recurrence_end_date, organization_id, block_type) FROM stdin;
\.


--
-- Data for Name: appointments_clinicevent; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.appointments_clinicevent (id, name, description, is_active) FROM stdin;
\.


--
-- Data for Name: appointments_environmentsetting; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.appointments_environmentsetting (id, blocked_days, updated_at) FROM stdin;
\.


--
-- Data for Name: appointments_holiday; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.appointments_holiday (id, name, date, is_recognized, suppressed) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Password Reset Token	6	add_resetpasswordtoken
22	Can change Password Reset Token	6	change_resetpasswordtoken
23	Can delete Password Reset Token	6	delete_resetpasswordtoken
24	Can view Password Reset Token	6	view_resetpasswordtoken
25	Can add user	7	add_customuser
26	Can change user	7	change_customuser
27	Can delete user	7	delete_customuser
28	Can view user	7	view_customuser
29	Can add patient	8	add_patient
30	Can change patient	8	change_patient
31	Can delete patient	8	delete_patient
32	Can view patient	8	view_patient
33	Can add organization	9	add_organization
34	Can change organization	9	change_organization
35	Can delete organization	9	delete_organization
36	Can view organization	9	view_organization
37	Can add Chat Room	10	add_chatroom
38	Can change Chat Room	10	change_chatroom
39	Can delete Chat Room	10	delete_chatroom
40	Can view Chat Room	10	view_chatroom
41	Can add Chat Message	11	add_chatmessage
42	Can change Chat Message	11	change_chatmessage
43	Can delete Chat Message	11	delete_chatmessage
44	Can view Chat Message	11	view_chatmessage
45	Can add Typing Indicator	12	add_typingindicator
46	Can change Typing Indicator	12	change_typingindicator
47	Can delete Typing Indicator	12	delete_typingindicator
48	Can view Typing Indicator	12	view_typingindicator
49	Can add appointment	13	add_appointment
50	Can change appointment	13	change_appointment
51	Can delete appointment	13	delete_appointment
52	Can view appointment	13	view_appointment
53	Can add availability	14	add_availability
54	Can change availability	14	change_availability
55	Can delete availability	14	delete_availability
56	Can view availability	14	view_availability
57	Can add environment setting	15	add_environmentsetting
58	Can change environment setting	15	change_environmentsetting
59	Can delete environment setting	15	delete_environmentsetting
60	Can view environment setting	15	view_environmentsetting
61	Can add holiday	16	add_holiday
62	Can change holiday	16	change_holiday
63	Can delete holiday	16	delete_holiday
64	Can view holiday	16	view_holiday
65	Can add clinic event	17	add_clinicevent
66	Can change clinic event	17	change_clinicevent
67	Can delete clinic event	17	delete_clinicevent
68	Can view clinic event	17	view_clinicevent
69	Can add auto email	18	add_autoemail
70	Can change auto email	18	change_autoemail
71	Can delete auto email	18	delete_autoemail
72	Can view auto email	18	view_autoemail
73	Can add contact	19	add_contact
74	Can change contact	19	change_contact
75	Can delete contact	19	delete_contact
76	Can view contact	19	view_contact
77	Can add message log	20	add_messagelog
78	Can change message log	20	change_messagelog
79	Can delete message log	20	delete_messagelog
80	Can view message log	20	view_messagelog
81	Can add cron job log	21	add_cronjoblog
82	Can change cron job log	21	change_cronjoblog
83	Can delete cron job log	21	delete_cronjoblog
84	Can view cron job log	21	view_cronjoblog
85	Can add cron job lock	22	add_cronjoblock
86	Can change cron job lock	22	change_cronjoblock
87	Can delete cron job lock	22	delete_cronjoblock
88	Can view cron job lock	22	view_cronjoblock
89	Can add online user	23	add_onlineuser
90	Can change online user	23	change_onlineuser
91	Can delete online user	23	delete_onlineuser
92	Can view online user	23	view_onlineuser
\.


--
-- Data for Name: communicator_contact; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.communicator_contact (id, name, phone, email, created_at, uploaded_by_id) FROM stdin;
\.


--
-- Data for Name: communicator_messagelog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.communicator_messagelog (id, recipient, subject, body, message_type, status, provider_id, created_at, user_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	django_rest_passwordreset	resetpasswordtoken
7	users	customuser
8	users	patient
9	users	organization
10	users	chatroom
11	users	chatmessage
12	users	typingindicator
13	appointments	appointment
14	appointments	availability
15	appointments	environmentsetting
16	appointments	holiday
17	appointments	clinicevent
18	appointments	autoemail
19	communicator	contact
20	communicator	messagelog
21	django_cron	cronjoblog
22	django_cron	cronjoblock
23	users	onlineuser
\.


--
-- Data for Name: django_cron_cronjoblock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_cron_cronjoblock (id, job_name, locked) FROM stdin;
\.


--
-- Data for Name: django_cron_cronjoblog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_cron_cronjoblog (id, code, start_time, end_time, is_success, message, ran_at_time) FROM stdin;
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-06-16 04:42:04.931486+00
2	contenttypes	0002_remove_content_type_name	2025-06-16 04:42:04.937324+00
3	auth	0001_initial	2025-06-16 04:42:04.997013+00
4	auth	0002_alter_permission_name_max_length	2025-06-16 04:42:05.002896+00
5	auth	0003_alter_user_email_max_length	2025-06-16 04:42:05.010214+00
6	auth	0004_alter_user_username_opts	2025-06-16 04:42:05.018785+00
7	auth	0005_alter_user_last_login_null	2025-06-16 04:42:05.025082+00
8	auth	0006_require_contenttypes_0002	2025-06-16 04:42:05.029486+00
9	auth	0007_alter_validators_add_error_messages	2025-06-16 04:42:05.036052+00
10	auth	0008_alter_user_username_max_length	2025-06-16 04:42:05.040797+00
11	auth	0009_alter_user_last_name_max_length	2025-06-16 04:42:05.045316+00
12	auth	0010_alter_group_name_max_length	2025-06-16 04:42:05.051829+00
13	auth	0011_update_proxy_permissions	2025-06-16 04:42:05.056896+00
14	auth	0012_alter_user_first_name_max_length	2025-06-16 04:42:05.063429+00
15	users	0001_initial	2025-06-16 04:42:05.137041+00
16	admin	0001_initial	2025-06-16 04:42:05.163355+00
17	admin	0002_logentry_remove_auto_add	2025-06-16 04:42:05.169931+00
18	admin	0003_logentry_add_action_flag_choices	2025-06-16 04:42:05.176166+00
19	users	0002_remove_customuser_is_doctor_and_more	2025-06-16 04:42:05.188343+00
20	users	0003_customuser_provider	2025-06-16 04:42:05.202897+00
21	users	0004_alter_customuser_role	2025-06-16 04:42:05.208117+00
22	users	0005_patient	2025-06-16 04:42:05.233101+00
23	users	0006_customuser_profile_picture	2025-06-16 04:42:05.24047+00
24	users	0007_customuser_phone_number	2025-06-16 04:42:05.248803+00
25	users	0008_organization	2025-06-16 04:42:05.259119+00
26	users	0009_customuser_organization	2025-06-16 04:42:05.277097+00
27	users	0010_alter_customuser_role	2025-06-16 04:42:05.285205+00
28	users	0011_alter_customuser_role	2025-06-16 04:42:05.292947+00
29	users	0012_patient_organization	2025-06-16 04:42:05.309066+00
30	users	0013_customuser_organization_type	2025-06-16 04:42:05.318027+00
31	users	0014_add_registered_field	2025-06-16 04:42:05.325125+00
32	users	0015_add_subscription_fields	2025-06-16 04:42:05.354581+00
33	appointments	0001_initial	2025-06-16 04:42:05.381411+00
34	appointments	0002_appointment_recurrence	2025-06-16 04:42:05.391062+00
35	appointments	0003_appointment_provider	2025-06-16 04:42:05.407015+00
36	appointments	0004_availability	2025-06-16 04:42:05.429636+00
37	appointments	0005_alter_availability_recurrence	2025-06-16 04:42:05.437786+00
38	appointments	0006_availability_recurrence_end_date	2025-06-16 04:42:05.4474+00
39	appointments	0007_environmentsetting	2025-06-16 04:42:05.461453+00
40	appointments	0008_environmentsetting_holidays	2025-06-16 04:42:05.466748+00
41	appointments	0009_holiday_remove_environmentsetting_holidays	2025-06-16 04:42:05.475999+00
42	appointments	0010_clinicevent	2025-06-16 04:42:05.501295+00
43	appointments	0011_appointment_organization	2025-06-16 04:42:05.519112+00
44	appointments	0012_availability_organization	2025-06-16 04:42:05.539184+00
45	appointments	0013_appointment_status	2025-06-16 04:42:05.549838+00
46	appointments	0014_holiday_unique_holiday	2025-06-16 04:42:05.559316+00
47	appointments	0015_holiday_suppressed	2025-06-16 04:42:05.565425+00
48	appointments	0016_availability_block_type	2025-06-16 04:42:05.574341+00
49	appointments	0017_appointment_recurrence_end_date	2025-06-16 04:42:05.582836+00
50	appointments	0018_autoemail	2025-06-16 04:42:05.605178+00
51	appointments	0019_appointment_arrived_appointment_no_show	2025-06-16 04:42:05.622219+00
52	appointments	0020_alter_autoemail_auto_message_frequency	2025-06-16 04:42:05.63007+00
53	communicator	0001_initial	2025-06-16 04:42:05.654955+00
54	communicator	0002_messagelog	2025-06-16 04:42:05.683343+00
55	django_cron	0001_initial	2025-06-16 04:42:05.733372+00
56	django_cron	0002_remove_max_length_from_CronJobLog_message	2025-06-16 04:42:05.738136+00
57	django_cron	0003_cronjoblock	2025-06-16 04:42:05.76159+00
58	django_rest_passwordreset	0001_initial	2025-06-16 04:42:05.799304+00
59	django_rest_passwordreset	0002_pk_migration	2025-06-16 04:42:05.855105+00
60	django_rest_passwordreset	0003_allow_blank_and_null_fields	2025-06-16 04:42:05.870996+00
61	django_rest_passwordreset	0004_alter_resetpasswordtoken_user_agent	2025-06-16 04:42:05.881806+00
62	sessions	0001_initial	2025-06-16 04:42:05.9071+00
63	users	0016_alter_patient_medical_history	2025-06-16 04:42:05.918977+00
64	users	0017_customuser_is_online_customuser_last_seen	2025-06-16 04:42:05.937086+00
65	users	0018_chat_models	2025-06-16 04:42:06.092986+00
66	users	0003_chat_models	2025-06-16 04:44:46.023398+00
67	users	0019_merge_0003_chat_models_0018_chat_models	2025-06-16 04:45:12.750563+00
68	users	0020_onlineuser_alter_typingindicator_options_and_more	2025-06-16 04:45:12.815041+00
\.


--
-- Data for Name: django_rest_passwordreset_resetpasswordtoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_rest_passwordreset_resetpasswordtoken (created_at, key, ip_address, user_agent, user_id, id) FROM stdin;
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
54agd8uodr4eksf8g9wrsqe7063cond7	.eJxVjMsOwiAQRf-FtSE8B-rSvd9ABhikaiAp7cr479qkC93ec859sYDbWsM2aAlzZmcm2el3i5ge1HaQ79hunafe1mWOfFf4QQe_9kzPy-H-HVQc9Vtba2VyRluVhdfOE2Qw3nivNQHFyaE25GKhJF0WMAlICkuxIJTRSkT2_gC2iTbv:1uR20p:zkoVF5WW6bQXYHrXG7h7nMKBFLJznopWiutOuBCSjEA	2025-06-30 05:04:03.95361+00
\.


--
-- Data for Name: users_chatmessage; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_chatmessage (id, message, message_type, "timestamp", is_read, recipient_id, room_id, sender_id) FROM stdin;
\.


--
-- Data for Name: users_chatroom; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_chatroom (id, name, room_type, created_at, is_active) FROM stdin;
\.


--
-- Data for Name: users_chatroom_participants; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_chatroom_participants (id, chatroom_id, customuser_id) FROM stdin;
\.


--
-- Data for Name: users_customuser; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_customuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, provider_id, profile_picture, phone_number, organization_id, organization_type, registered, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_tier, trial_end_date, trial_start_date, is_online, last_seen) FROM stdin;
1	pbkdf2_sha256$600000$AIalPtHZkFACGWb6tsU9cE$PKceFTxdZMfwsYGvbsHaEG9hGoXUtWAdYOQzoNbEfTM=	2025-06-16 05:04:03.948913+00	t	jsswp2004			jsswp2004@outlook.com	t	t	2025-06-16 05:03:34.433183+00	none	\N		\N	\N	personal	f	\N	\N	trial	basic	\N	\N	f	\N
\.


--
-- Data for Name: users_customuser_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: users_onlineuser; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_onlineuser (user_id, is_online, last_seen) FROM stdin;
\.


--
-- Data for Name: users_organization; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_organization (id, name, logo, created_at) FROM stdin;
\.


--
-- Data for Name: users_patient; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_patient (id, date_of_birth, phone_number, address, medical_history, user_id, organization_id) FROM stdin;
\.


--
-- Data for Name: users_typingindicator; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_typingindicator (id, is_typing, last_typing_time, room_id, user_id) FROM stdin;
\.


--
-- Name: appointments_appointment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointments_appointment_id_seq', 1, false);


--
-- Name: appointments_autoemail_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointments_autoemail_id_seq', 1, false);


--
-- Name: appointments_availability_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointments_availability_id_seq', 1, false);


--
-- Name: appointments_clinicevent_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointments_clinicevent_id_seq', 1, false);


--
-- Name: appointments_environmentsetting_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointments_environmentsetting_id_seq', 1, false);


--
-- Name: appointments_holiday_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointments_holiday_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 92, true);


--
-- Name: communicator_contact_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.communicator_contact_id_seq', 1, false);


--
-- Name: communicator_messagelog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.communicator_messagelog_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 23, true);


--
-- Name: django_cron_cronjoblock_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_cron_cronjoblock_id_seq', 1, false);


--
-- Name: django_cron_cronjoblog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_cron_cronjoblog_id_seq', 1, false);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 68, true);


--
-- Name: django_rest_passwordreset_resetpasswordtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_rest_passwordreset_resetpasswordtoken_id_seq', 1, false);


--
-- Name: users_chatmessage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_chatmessage_id_seq', 1, false);


--
-- Name: users_chatroom_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_chatroom_id_seq', 1, false);


--
-- Name: users_chatroom_participants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_chatroom_participants_id_seq', 1, false);


--
-- Name: users_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_customuser_groups_id_seq', 1, false);


--
-- Name: users_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_customuser_id_seq', 1, true);


--
-- Name: users_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_customuser_user_permissions_id_seq', 1, false);


--
-- Name: users_organization_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_organization_id_seq', 1, false);


--
-- Name: users_patient_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_patient_id_seq', 1, false);


--
-- Name: users_typingindicator_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_typingindicator_id_seq', 1, false);


--
-- Name: appointments_appointment appointments_appointment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_appointment
    ADD CONSTRAINT appointments_appointment_pkey PRIMARY KEY (id);


--
-- Name: appointments_autoemail appointments_autoemail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_autoemail
    ADD CONSTRAINT appointments_autoemail_pkey PRIMARY KEY (id);


--
-- Name: appointments_availability appointments_availability_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_availability
    ADD CONSTRAINT appointments_availability_pkey PRIMARY KEY (id);


--
-- Name: appointments_clinicevent appointments_clinicevent_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_clinicevent
    ADD CONSTRAINT appointments_clinicevent_name_key UNIQUE (name);


--
-- Name: appointments_clinicevent appointments_clinicevent_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_clinicevent
    ADD CONSTRAINT appointments_clinicevent_pkey PRIMARY KEY (id);


--
-- Name: appointments_environmentsetting appointments_environmentsetting_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_environmentsetting
    ADD CONSTRAINT appointments_environmentsetting_pkey PRIMARY KEY (id);


--
-- Name: appointments_holiday appointments_holiday_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_holiday
    ADD CONSTRAINT appointments_holiday_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: communicator_contact communicator_contact_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.communicator_contact
    ADD CONSTRAINT communicator_contact_pkey PRIMARY KEY (id);


--
-- Name: communicator_messagelog communicator_messagelog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.communicator_messagelog
    ADD CONSTRAINT communicator_messagelog_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_cron_cronjoblock django_cron_cronjoblock_job_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_cron_cronjoblock
    ADD CONSTRAINT django_cron_cronjoblock_job_name_key UNIQUE (job_name);


--
-- Name: django_cron_cronjoblock django_cron_cronjoblock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_cron_cronjoblock
    ADD CONSTRAINT django_cron_cronjoblock_pkey PRIMARY KEY (id);


--
-- Name: django_cron_cronjoblog django_cron_cronjoblog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_cron_cronjoblog
    ADD CONSTRAINT django_cron_cronjoblog_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_rest_passwordreset_resetpasswordtoken django_rest_passwordreset_resetpasswordtoken_key_f1b65873_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_rest_passwordreset_resetpasswordtoken
    ADD CONSTRAINT django_rest_passwordreset_resetpasswordtoken_key_f1b65873_uniq UNIQUE (key);


--
-- Name: django_rest_passwordreset_resetpasswordtoken django_rest_passwordreset_resetpasswordtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_rest_passwordreset_resetpasswordtoken
    ADD CONSTRAINT django_rest_passwordreset_resetpasswordtoken_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: appointments_holiday unique_holiday; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_holiday
    ADD CONSTRAINT unique_holiday UNIQUE (name, date);


--
-- Name: users_chatmessage users_chatmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_chatmessage
    ADD CONSTRAINT users_chatmessage_pkey PRIMARY KEY (id);


--
-- Name: users_chatroom_participants users_chatroom_participa_chatroom_id_customuser_i_370b91ca_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_chatroom_participants
    ADD CONSTRAINT users_chatroom_participa_chatroom_id_customuser_i_370b91ca_uniq UNIQUE (chatroom_id, customuser_id);


--
-- Name: users_chatroom_participants users_chatroom_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_chatroom_participants
    ADD CONSTRAINT users_chatroom_participants_pkey PRIMARY KEY (id);


--
-- Name: users_chatroom users_chatroom_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_chatroom
    ADD CONSTRAINT users_chatroom_pkey PRIMARY KEY (id);


--
-- Name: users_customuser_groups users_customuser_groups_customuser_id_group_id_76b619e3_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_customuser_id_group_id_76b619e3_uniq UNIQUE (customuser_id, group_id);


--
-- Name: users_customuser_groups users_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: users_customuser users_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_pkey PRIMARY KEY (id);


--
-- Name: users_customuser_user_permissions users_customuser_user_pe_customuser_id_permission_7a7debf6_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_user_pe_customuser_id_permission_7a7debf6_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: users_customuser_user_permissions users_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_customuser users_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_username_key UNIQUE (username);


--
-- Name: users_onlineuser users_onlineuser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_onlineuser
    ADD CONSTRAINT users_onlineuser_pkey PRIMARY KEY (user_id);


--
-- Name: users_organization users_organization_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_organization
    ADD CONSTRAINT users_organization_pkey PRIMARY KEY (id);


--
-- Name: users_patient users_patient_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_patient
    ADD CONSTRAINT users_patient_pkey PRIMARY KEY (id);


--
-- Name: users_patient users_patient_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_patient
    ADD CONSTRAINT users_patient_user_id_key UNIQUE (user_id);


--
-- Name: users_typingindicator users_typingindicator_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_typingindicator
    ADD CONSTRAINT users_typingindicator_pkey PRIMARY KEY (id);


--
-- Name: users_typingindicator users_typingindicator_user_id_room_id_533d5daf_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_typingindicator
    ADD CONSTRAINT users_typingindicator_user_id_room_id_533d5daf_uniq UNIQUE (user_id, room_id);


--
-- Name: appointments_appointment_organization_id_6a52787b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX appointments_appointment_organization_id_6a52787b ON public.appointments_appointment USING btree (organization_id);


--
-- Name: appointments_appointment_patient_id_631d13da; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX appointments_appointment_patient_id_631d13da ON public.appointments_appointment USING btree (patient_id);


--
-- Name: appointments_appointment_provider_id_301e66b6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX appointments_appointment_provider_id_301e66b6 ON public.appointments_appointment USING btree (provider_id);


--
-- Name: appointments_autoemail_organization_id_cd3e2cc9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX appointments_autoemail_organization_id_cd3e2cc9 ON public.appointments_autoemail USING btree (organization_id);


--
-- Name: appointments_availability_doctor_id_91d8cc63; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX appointments_availability_doctor_id_91d8cc63 ON public.appointments_availability USING btree (doctor_id);


--
-- Name: appointments_availability_organization_id_99a27dd9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX appointments_availability_organization_id_99a27dd9 ON public.appointments_availability USING btree (organization_id);


--
-- Name: appointments_clinicevent_name_52e9d447_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX appointments_clinicevent_name_52e9d447_like ON public.appointments_clinicevent USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: communicator_contact_uploaded_by_id_f2a5835b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX communicator_contact_uploaded_by_id_f2a5835b ON public.communicator_contact USING btree (uploaded_by_id);


--
-- Name: communicator_messagelog_user_id_0f867060; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX communicator_messagelog_user_id_0f867060 ON public.communicator_messagelog USING btree (user_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_cron_cronjoblock_job_name_fb6ce879_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblock_job_name_fb6ce879_like ON public.django_cron_cronjoblock USING btree (job_name varchar_pattern_ops);


--
-- Name: django_cron_cronjoblog_code_48865653; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblog_code_48865653 ON public.django_cron_cronjoblog USING btree (code);


--
-- Name: django_cron_cronjoblog_code_48865653_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblog_code_48865653_like ON public.django_cron_cronjoblog USING btree (code varchar_pattern_ops);


--
-- Name: django_cron_cronjoblog_code_is_success_ran_at_time_84da9606_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblog_code_is_success_ran_at_time_84da9606_idx ON public.django_cron_cronjoblog USING btree (code, is_success, ran_at_time);


--
-- Name: django_cron_cronjoblog_code_start_time_4fc78f9d_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblog_code_start_time_4fc78f9d_idx ON public.django_cron_cronjoblog USING btree (code, start_time);


--
-- Name: django_cron_cronjoblog_code_start_time_ran_at_time_8b50b8fa_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblog_code_start_time_ran_at_time_8b50b8fa_idx ON public.django_cron_cronjoblog USING btree (code, start_time, ran_at_time);


--
-- Name: django_cron_cronjoblog_end_time_7918602a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblog_end_time_7918602a ON public.django_cron_cronjoblog USING btree (end_time);


--
-- Name: django_cron_cronjoblog_ran_at_time_7fed2751; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblog_ran_at_time_7fed2751 ON public.django_cron_cronjoblog USING btree (ran_at_time);


--
-- Name: django_cron_cronjoblog_start_time_d68c0dd9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblog_start_time_d68c0dd9 ON public.django_cron_cronjoblog USING btree (start_time);


--
-- Name: django_rest_passwordreset_resetpasswordtoken_key_f1b65873_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_rest_passwordreset_resetpasswordtoken_key_f1b65873_like ON public.django_rest_passwordreset_resetpasswordtoken USING btree (key varchar_pattern_ops);


--
-- Name: django_rest_passwordreset_resetpasswordtoken_user_id_e8015b11; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_rest_passwordreset_resetpasswordtoken_user_id_e8015b11 ON public.django_rest_passwordreset_resetpasswordtoken USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: users_chatmessage_recipient_id_4ed7fcfc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_chatmessage_recipient_id_4ed7fcfc ON public.users_chatmessage USING btree (recipient_id);


--
-- Name: users_chatmessage_room_id_0296ac6f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_chatmessage_room_id_0296ac6f ON public.users_chatmessage USING btree (room_id);


--
-- Name: users_chatmessage_sender_id_07628830; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_chatmessage_sender_id_07628830 ON public.users_chatmessage USING btree (sender_id);


--
-- Name: users_chatroom_participants_chatroom_id_cfe7e127; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_chatroom_participants_chatroom_id_cfe7e127 ON public.users_chatroom_participants USING btree (chatroom_id);


--
-- Name: users_chatroom_participants_customuser_id_ca50a5ae; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_chatroom_participants_customuser_id_ca50a5ae ON public.users_chatroom_participants USING btree (customuser_id);


--
-- Name: users_customuser_groups_customuser_id_958147bf; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_customuser_groups_customuser_id_958147bf ON public.users_customuser_groups USING btree (customuser_id);


--
-- Name: users_customuser_groups_group_id_01390b14; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_customuser_groups_group_id_01390b14 ON public.users_customuser_groups USING btree (group_id);


--
-- Name: users_customuser_organization_id_e9d85824; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_customuser_organization_id_e9d85824 ON public.users_customuser USING btree (organization_id);


--
-- Name: users_customuser_provider_id_de6c8304; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_customuser_provider_id_de6c8304 ON public.users_customuser USING btree (provider_id);


--
-- Name: users_customuser_user_permissions_customuser_id_5771478b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_customuser_user_permissions_customuser_id_5771478b ON public.users_customuser_user_permissions USING btree (customuser_id);


--
-- Name: users_customuser_user_permissions_permission_id_baaa2f74; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_customuser_user_permissions_permission_id_baaa2f74 ON public.users_customuser_user_permissions USING btree (permission_id);


--
-- Name: users_customuser_username_80452fdf_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_customuser_username_80452fdf_like ON public.users_customuser USING btree (username varchar_pattern_ops);


--
-- Name: users_patient_organization_id_ac5c2644; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_patient_organization_id_ac5c2644 ON public.users_patient USING btree (organization_id);


--
-- Name: users_typingindicator_room_id_703d276c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_typingindicator_room_id_703d276c ON public.users_typingindicator USING btree (room_id);


--
-- Name: users_typingindicator_user_id_21171280; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_typingindicator_user_id_21171280 ON public.users_typingindicator USING btree (user_id);


--
-- Name: appointments_appointment appointments_appoint_organization_id_6a52787b_fk_users_org; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_appointment
    ADD CONSTRAINT appointments_appoint_organization_id_6a52787b_fk_users_org FOREIGN KEY (organization_id) REFERENCES public.users_organization(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_appointment appointments_appoint_patient_id_631d13da_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_appointment
    ADD CONSTRAINT appointments_appoint_patient_id_631d13da_fk_users_cus FOREIGN KEY (patient_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_appointment appointments_appoint_provider_id_301e66b6_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_appointment
    ADD CONSTRAINT appointments_appoint_provider_id_301e66b6_fk_users_cus FOREIGN KEY (provider_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_autoemail appointments_autoema_organization_id_cd3e2cc9_fk_users_org; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_autoemail
    ADD CONSTRAINT appointments_autoema_organization_id_cd3e2cc9_fk_users_org FOREIGN KEY (organization_id) REFERENCES public.users_organization(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_availability appointments_availab_doctor_id_91d8cc63_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_availability
    ADD CONSTRAINT appointments_availab_doctor_id_91d8cc63_fk_users_cus FOREIGN KEY (doctor_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_availability appointments_availab_organization_id_99a27dd9_fk_users_org; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_availability
    ADD CONSTRAINT appointments_availab_organization_id_99a27dd9_fk_users_org FOREIGN KEY (organization_id) REFERENCES public.users_organization(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: communicator_contact communicator_contact_uploaded_by_id_f2a5835b_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.communicator_contact
    ADD CONSTRAINT communicator_contact_uploaded_by_id_f2a5835b_fk_users_cus FOREIGN KEY (uploaded_by_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: communicator_messagelog communicator_messagelog_user_id_0f867060_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.communicator_messagelog
    ADD CONSTRAINT communicator_messagelog_user_id_0f867060_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_rest_passwordreset_resetpasswordtoken django_rest_password_user_id_e8015b11_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_rest_passwordreset_resetpasswordtoken
    ADD CONSTRAINT django_rest_password_user_id_e8015b11_fk_users_cus FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_chatmessage users_chatmessage_recipient_id_4ed7fcfc_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_chatmessage
    ADD CONSTRAINT users_chatmessage_recipient_id_4ed7fcfc_fk_users_customuser_id FOREIGN KEY (recipient_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_chatmessage users_chatmessage_room_id_0296ac6f_fk_users_chatroom_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_chatmessage
    ADD CONSTRAINT users_chatmessage_room_id_0296ac6f_fk_users_chatroom_id FOREIGN KEY (room_id) REFERENCES public.users_chatroom(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_chatmessage users_chatmessage_sender_id_07628830_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_chatmessage
    ADD CONSTRAINT users_chatmessage_sender_id_07628830_fk_users_customuser_id FOREIGN KEY (sender_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_chatroom_participants users_chatroom_parti_chatroom_id_cfe7e127_fk_users_cha; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_chatroom_participants
    ADD CONSTRAINT users_chatroom_parti_chatroom_id_cfe7e127_fk_users_cha FOREIGN KEY (chatroom_id) REFERENCES public.users_chatroom(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_chatroom_participants users_chatroom_parti_customuser_id_ca50a5ae_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_chatroom_participants
    ADD CONSTRAINT users_chatroom_parti_customuser_id_ca50a5ae_fk_users_cus FOREIGN KEY (customuser_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_groups users_customuser_gro_customuser_id_958147bf_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_gro_customuser_id_958147bf_fk_users_cus FOREIGN KEY (customuser_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_groups users_customuser_groups_group_id_01390b14_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_group_id_01390b14_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser users_customuser_organization_id_e9d85824_fk_users_org; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_organization_id_e9d85824_fk_users_org FOREIGN KEY (organization_id) REFERENCES public.users_organization(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser users_customuser_provider_id_de6c8304_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_provider_id_de6c8304_fk_users_customuser_id FOREIGN KEY (provider_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_user_permissions users_customuser_use_customuser_id_5771478b_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_use_customuser_id_5771478b_fk_users_cus FOREIGN KEY (customuser_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_user_permissions users_customuser_use_permission_id_baaa2f74_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_use_permission_id_baaa2f74_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_onlineuser users_onlineuser_user_id_fdb0b132_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_onlineuser
    ADD CONSTRAINT users_onlineuser_user_id_fdb0b132_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_patient users_patient_organization_id_ac5c2644_fk_users_organization_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_patient
    ADD CONSTRAINT users_patient_organization_id_ac5c2644_fk_users_organization_id FOREIGN KEY (organization_id) REFERENCES public.users_organization(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_patient users_patient_user_id_5ff17cf1_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_patient
    ADD CONSTRAINT users_patient_user_id_5ff17cf1_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_typingindicator users_typingindicator_room_id_703d276c_fk_users_chatroom_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_typingindicator
    ADD CONSTRAINT users_typingindicator_room_id_703d276c_fk_users_chatroom_id FOREIGN KEY (room_id) REFERENCES public.users_chatroom(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_typingindicator users_typingindicator_user_id_21171280_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_typingindicator
    ADD CONSTRAINT users_typingindicator_user_id_21171280_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

