# Generated by Django 5.2 on 2025-05-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_availability_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
