# Generated by Django 5.2 on 2025-05-22 04:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_availability_recurrence_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='Days blocked by default, 0=Sun, ..., 6=Sat', size=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
