# Generated by Django 5.2 on 2025-05-22 17:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_environmentsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentsetting',
            name='holidays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None),
        ),
    ]
