# Generated by Django 5.2 on 2025-05-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_environmentsetting_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('is_recognized', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='environmentsetting',
            name='holidays',
        ),
    ]
