# Generated by Django 5.2 on 2025-05-26 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_appointment_organization'),
        ('users', '0009_customuser_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.organization'),
        ),
    ]
