# Generated by Django 5.2 on 2025-05-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_availability_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled'), ('pending', 'Pending'), ('in_progress', 'In Progress')], default='scheduled', help_text='Status of the appointment', max_length=20),
        ),
    ]
