# Generated by Django 5.2 on 2025-05-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_holiday_unique_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='suppressed',
            field=models.BooleanField(default=False),
        ),
    ]
