# Generated by Django 5.2 on 2025-06-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_holiday_suppressed'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='block_type',
            field=models.CharField(blank=True, choices=[('Lunch', 'Lunch'), ('Meeting', 'Meeting'), ('Vacation', 'Vacation'), ('On Leave', 'On Leave'), ('Other', 'Other')], default='Lunch', help_text='Type of block for this availability (if blocked)', max_length=32, null=True),
        ),
    ]
