# Generated by Django 5.2 on 2025-06-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_availability_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
