# Generated by Django 5.2 on 2025-06-06 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_appointment_recurrence_end_date'),
        ('users', '0015_add_subscription_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_message_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('bi-weekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='weekly', help_text='How often automated emails should be sent', max_length=20)),
                ('auto_message_day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=1, help_text='Day of the week when automated emails should be sent')),
                ('auto_message_start_date', models.DateField(blank=True, help_text='When to start sending automated emails', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether automated emails are enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this auto email setting belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_emails', to='users.organization')),
            ],
        ),
    ]
