# Generated by Django 4.2 on 2025-06-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_appointment_recurrence_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_message_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('bi-weekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='weekly', help_text='How often to send auto emails', max_length=20)),
                ('auto_message_day_of_week', models.IntegerField(default=1, help_text='Day of week to send (0=Sunday, 1=Monday, ... 6=Saturday)')),
                ('auto_message_start_date', models.DateField(blank=True, help_text='When to start sending automated emails', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether automated emails are enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
