# Generated by Django 4.2 on 2025-06-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_appointment_arrived_appointment_no_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoemail',
            name='auto_message_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='weekly', help_text='How often automated emails should be sent', max_length=20),
        ),
    ]
