# Generated by Django 4.2 on 2025-07-05 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_add_sms_consent_fields'),
        ('appointments', '0020_alter_autoemail_auto_message_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentsetting',
            name='organization',
            field=models.OneToOneField(blank=True, help_text='Organization this setting belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environment_setting', to='users.organization'),
        ),
    ]
