# Generated by Django 4.2 on 2025-07-05 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_add_sms_consent_fields'),
        ('appointments', '0021_environmentsetting_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentsetting',
            name='organization',
            field=models.OneToOneField(help_text='Organization this setting belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='environment_setting', to='users.organization'),
        ),
    ]
