# Generated by Django 4.2 on 2025-08-30 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_organization_max_users_and_more'),
        ('appointments', '0022_alter_environmentsetting_organization'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='holiday',
            name='unique_holiday',
        ),
        migrations.AddField(
            model_name='holiday',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='users.organization'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('organization', 'name', 'date'), name='unique_holiday_per_org'),
        ),
    ]
