# Generated by Django 4.2 on 2025-08-30 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_organization_max_users_and_more'),
        ('appointments', '0023_remove_holiday_unique_holiday_holiday_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicevent',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this clinic event belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_events', to='users.organization'),
        ),
    ]
