# Generated by Django 4.2 on 2025-08-30 19:31

from django.db import migrations


def populate_clinic_event_organizations(apps, schema_editor):
    """
    Duplicate existing clinic events for each organization.
    Since clinic events were previously global, we want them available to all organizations.
    """
    ClinicEvent = apps.get_model("appointments", "ClinicEvent")
    Organization = apps.get_model("users", "Organization")

    # Get all existing clinic events (they should have organization=None)
    global_events = ClinicEvent.objects.filter(organization__isnull=True)

    if not global_events.exists():
        return  # No global events to migrate

    # Get all organizations
    organizations = Organization.objects.all()

    if not organizations.exists():
        return  # No organizations to assign to

    print(
        f"Migrating {global_events.count()} clinic events to {organizations.count()} organizations..."
    )

    # For each organization, create copies of all global clinic events
    for org in organizations:
        for event in global_events:
            # Create a copy for this organization
            ClinicEvent.objects.create(
                name=event.name,
                description=event.description,
                is_active=event.is_active,
                organization=org,
            )
            print(f"Created '{event.name}' for {org.name}")

    # Delete the original global events (organization=None)
    global_events.delete()
    print("Deleted original global clinic events")


def reverse_populate_clinic_event_organizations(apps, schema_editor):
    """
    Reverse migration: Convert organization-specific events back to global events.
    This will keep only one copy of each unique event name.
    """
    ClinicEvent = apps.get_model("appointments", "ClinicEvent")

    # Get all unique event names
    unique_names = ClinicEvent.objects.values_list("name", flat=True).distinct()

    # For each unique name, keep one copy and make it global
    for name in unique_names:
        first_event = ClinicEvent.objects.filter(name=name).first()
        if first_event:
            # Create a global version
            ClinicEvent.objects.create(
                name=first_event.name,
                description=first_event.description,
                is_active=first_event.is_active,
                organization=None,
            )

    # Delete all organization-specific events
    ClinicEvent.objects.filter(organization__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0024_add_organization_to_clinicevent"),
    ]

    operations = [
        migrations.RunPython(
            populate_clinic_event_organizations,
            reverse_populate_clinic_event_organizations,
        ),
    ]
