# Generated by Django 4.2 on 2025-08-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0024_add_organization_to_clinicevent'),
    ]

    operations = [
        # First remove the unique constraint on name
        migrations.AlterField(
            model_name='clinicevent',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
