# Generated by Django 4.2 on 2025-08-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0025_populate_clinicevent_organizations"),
    ]

    operations = [
        # Remove the unique constraint on name to allow multiple organizations to have the same event name
        migrations.AlterField(
            model_name="clinicevent",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
