# Generated by Django 4.2 on 2025-08-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_organization_max_users_and_more'),
        ('appointments', '0026_populate_clinicevent_organizations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clinicevent',
            unique_together={('name', 'organization')},
        ),
    ]
