# Generated by Django 4.2 on 2026-09-26 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_customuser_add_nurse_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointments", "0035_notefielddefinition_tab_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="VitalSignsFlowsheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("columns", models.JSONField(blank=True, default=list)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        help_text="The visit this flowsheet charts vitals for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_signs_flowsheet",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_signs_flowsheets",
                        to="users.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vital_signs_flowsheets_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
