# Generated by Django 4.2 on 2026-09-26 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointments", "0036_vitalsignsflowsheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalsignsflowsheet",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vital_signs_flowsheets_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
