# Generated by Django 4.2 on 2026-10-05 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0032_organization_lab_interface_enabled"),
        ("appointments", "0044_lab_scanned_documents"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabInterfaceConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label for staff, e.g. Quest HL7 feed", max_length=100
                    ),
                ),
                (
                    "lab_name",
                    models.CharField(
                        blank=True,
                        help_text="Shown on results, e.g. Quest Diagnostics",
                        max_length=120,
                    ),
                ),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                ("key_prefix", models.CharField(blank=True, max_length=12)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_connections",
                        to="users.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabInboundMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_format",
                    models.CharField(
                        choices=[("hl7", "HL7 v2"), ("fhir", "FHIR")], max_length=4
                    ),
                ),
                ("control_id", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processed", "Filed"),
                            ("unmatched", "Needs a patient"),
                            ("assigned", "Assigned by staff"),
                            ("dismissed", "Dismissed by staff"),
                            ("rejected", "Rejected"),
                            ("ignored", "Nothing to file"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True, help_text="Why it was not filed, or what was done"
                    ),
                ),
                (
                    "patient_hint",
                    models.CharField(
                        blank=True,
                        help_text="Name / DOB / MRN as the lab sent them",
                        max_length=255,
                    ),
                ),
                ("raw", models.TextField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="appointments.labinterfaceconnection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_inbound_messages",
                        to="users.organization",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_messages_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="labreport",
            name="inbound_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="appointments.labinboundmessage",
            ),
        ),
        migrations.AddIndex(
            model_name="labinboundmessage",
            index=models.Index(
                fields=["organization", "status"], name="appointment_organiz_ecad5a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="labinboundmessage",
            unique_together={("connection", "control_id")},
        ),
    ]
