# Generated by Django 4.2 on 2026-10-05 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_lab_orders_out"),
        ("appointments", "0045_lab_interface"),
    ]

    operations = [
        migrations.AddField(
            model_name="labinterfaceconnection",
            name="send_orders",
            field=models.BooleanField(
                default=False,
                help_text="Also send this clinic's lab orders to this lab. At most one connection per clinic.",
            ),
        ),
        migrations.CreateModel(
            name="LabOutboundMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("NW", "New order"), ("CA", "Cancel order")],
                        max_length=2,
                    ),
                ),
                ("control_id", models.CharField(max_length=40, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting to be picked up"),
                            ("delivered", "Picked up, not yet confirmed"),
                            ("acknowledged", "Accepted by the lab"),
                            ("rejected", "Rejected by the lab"),
                            ("cancelled", "Withdrawn before it was sent"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "last_body",
                    models.TextField(
                        blank=True, help_text="The message as last handed over"
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("delivery_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_messages",
                        to="appointments.labinterfaceconnection",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_outbound_messages",
                        to="appointments.order",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_outbound_messages",
                        to="users.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="laboutboundmessage",
            index=models.Index(
                fields=["connection", "status"], name="appointment_connect_09bc97_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="laboutboundmessage",
            unique_together={("order", "action")},
        ),
    ]
