# Generated by Django 4.2 on 2026-10-08 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_registration_resident_provider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointments", "0051_referrals"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_type", models.CharField(default="medication", max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("dose", models.CharField(blank=True, max_length=120)),
                ("route", models.CharField(blank=True, max_length=40)),
                ("instructions", models.TextField(blank=True)),
                ("frequency", models.CharField(blank=True, max_length=20)),
                ("due_at", models.DateTimeField()),
                ("is_prn", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "To do"),
                            ("done", "Done"),
                            ("held", "Held"),
                            ("refused", "Refused"),
                            ("missed", "Missed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("performed_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("note", models.TextField(blank=True)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["due_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="schedule",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="How often and when it is given/done: frequency, dose, route, first_due, stop_at... ({} = no nurse tasks)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tasks_generated_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderable",
            name="creates_tasks",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Nurse tasks: blank follows the category (medications and nursing orders), yes always, no never",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderable",
            name="default_frequency",
            field=models.CharField(
                blank=True,
                help_text="Optional frequency offered first when this is ordered (e.g. bid, q8h)",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TaskSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grace_minutes", models.PositiveIntegerField(default=60)),
                ("missed_after_hours", models.PositiveIntegerField(default=12)),
                ("look_ahead_hours", models.PositiveIntegerField(default=24)),
                (
                    "pass_times",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="frequency -> list of HH:MM, e.g. {'bid': ['09:00','21:00']}",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_settings",
                        to="users.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderTaskEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=30)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="appointments.ordertask",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="ordertask",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="appointments.order",
            ),
        ),
        migrations.AddField(
            model_name="ordertask",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_tasks",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="ordertask",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ordertask",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_tasks_done",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="ordertask",
            index=models.Index(
                fields=["organization", "status", "due_at"],
                name="appointment_organiz_cf53b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ordertask",
            index=models.Index(
                fields=["patient", "due_at"], name="appointment_patient_be4fe6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ordertask",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_prn", False)),
                fields=("order", "due_at"),
                name="uniq_order_task_slot",
            ),
        ),
    
    ]
