# Generated by Django 4.2 on 2026-10-09 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0039_registration_resident_provider"),
        ("appointments", "0053_task_grid_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("fax", models.CharField(blank=True, max_length=30)),
                ("ncpdp_id", models.CharField(blank=True, max_length=7)),
                ("npi", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacies",
                        to="users.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "pharmacies",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_name", models.CharField(max_length=200)),
                ("code_system", models.CharField(blank=True, max_length=10)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("strength", models.CharField(blank=True, max_length=60)),
                ("form", models.CharField(blank=True, max_length=40)),
                ("dose", models.CharField(blank=True, max_length=60)),
                ("route", models.CharField(blank=True, max_length=20)),
                ("frequency", models.CharField(blank=True, max_length=10)),
                ("duration_days", models.PositiveIntegerField(blank=True, null=True)),
                ("prn", models.BooleanField(default=False)),
                ("prn_reason", models.CharField(blank=True, max_length=120)),
                ("sig_extra", models.CharField(blank=True, max_length=300)),
                ("sig", models.CharField(blank=True, max_length=500)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("quantity_unit", models.CharField(blank=True, max_length=30)),
                ("days_supply", models.PositiveIntegerField(blank=True, null=True)),
                ("refills", models.PositiveSmallIntegerField(default=0)),
                ("dispense_as_written", models.BooleanField(default=False)),
                ("indication_code", models.CharField(blank=True, max_length=20)),
                ("indication_text", models.CharField(blank=True, max_length=255)),
                ("note_to_pharmacist", models.CharField(blank=True, max_length=500)),
                ("pharmacy_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("signed", "Signed"),
                            ("sent", "Given / sent"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not yet"),
                            ("print", "Printed"),
                            ("fax", "Faxed"),
                            ("erx", "Electronic"),
                        ],
                        max_length=6,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_detail", models.JSONField(blank=True, default=dict)),
                ("print_count", models.PositiveIntegerField(default=0)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=300)),
                ("clinical_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AlterModelOptions(
            name="appointment",
            options={"base_manager_name": "all_objects"},
        ),
        migrations.AlterModelManagers(
            name="appointment",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PrescriptionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=30)),
                ("from_status", models.CharField(blank=True, max_length=10)),
                ("to_status", models.CharField(blank=True, max_length=10)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="appointments.prescription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="prescription",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prescriptions_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="pharmacy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescriptions",
                to="appointments.pharmacy",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="prescriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prescriptions_written",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="replaces",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaced_by",
                to="appointments.prescription",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="signed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PrescriberProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(blank=True, max_length=40)),
                ("license_state", models.CharField(blank=True, max_length=2)),
                ("dea_number", models.CharField(blank=True, max_length=15)),
                ("practice_name", models.CharField(blank=True, max_length=200)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("fax", models.CharField(blank=True, max_length=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriber_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientPharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_pharmacy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="appointments.pharmacy",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["organization", "status"], name="appointment_organiz_81d818_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["patient", "status"], name="appointment_patient_d8eb7a_idx"
            ),
        ),
    ]
