# Generated by Django 4.2 on 2026-10-09 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_registration_resident_provider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointments", "0054_prescriptions"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("snapshot", models.JSONField(blank=True, default=list)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="med_reviews",
                        to="users.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="med_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HomeMedication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_name", models.CharField(max_length=200)),
                ("code_system", models.CharField(blank=True, max_length=10)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("strength", models.CharField(blank=True, max_length=60)),
                ("form", models.CharField(blank=True, max_length=40)),
                ("dose", models.CharField(blank=True, max_length=60)),
                ("route", models.CharField(blank=True, max_length=20)),
                ("frequency", models.CharField(blank=True, max_length=10)),
                ("prn", models.BooleanField(default=False)),
                ("prn_reason", models.CharField(blank=True, max_length=120)),
                ("sig_extra", models.CharField(blank=True, max_length=300)),
                ("indication_text", models.CharField(blank=True, max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("patient", "Patient"),
                            ("family", "Family or caregiver"),
                            ("pharmacy", "Pharmacy record"),
                            ("outside", "Outside records"),
                            ("our_rx", "Our prescription"),
                        ],
                        default="patient",
                        max_length=10,
                    ),
                ),
                ("outside_prescriber", models.CharField(blank=True, max_length=120)),
                ("last_taken", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Taking"), ("stopped", "Stopped")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("stop_reason", models.CharField(blank=True, max_length=255)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="home_entries",
                        to="appointments.prescription",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_medications",
                        to="users.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_medications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stopped_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["status", "drug_name", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="homemedication",
            index=models.Index(
                fields=["patient", "status"], name="appointment_patient_9de563_idx"
            ),
        ),
    ]
