# Generated by Django 4.2 on 2026-10-09 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0039_registration_resident_provider"),
        ("appointments", "0055_home_medications"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="renews",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renewed_by",
                to="appointments.prescription",
            ),
        ),
        migrations.CreateModel(
            name="PrescriptionFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=80)),
                ("drug_name", models.CharField(max_length=200)),
                ("code_system", models.CharField(blank=True, max_length=10)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("strength", models.CharField(blank=True, max_length=60)),
                ("form", models.CharField(blank=True, max_length=40)),
                ("dose", models.CharField(blank=True, max_length=60)),
                ("route", models.CharField(blank=True, max_length=20)),
                ("frequency", models.CharField(blank=True, max_length=10)),
                ("duration_days", models.PositiveIntegerField(blank=True, null=True)),
                ("prn", models.BooleanField(default=False)),
                ("prn_reason", models.CharField(blank=True, max_length=120)),
                ("sig_extra", models.CharField(blank=True, max_length=300)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("quantity_unit", models.CharField(blank=True, max_length=30)),
                ("days_supply", models.PositiveIntegerField(blank=True, null=True)),
                ("refills", models.PositiveSmallIntegerField(default=0)),
                ("dispense_as_written", models.BooleanField(default=False)),
                ("indication_code", models.CharField(blank=True, max_length=20)),
                ("indication_text", models.CharField(blank=True, max_length=255)),
                ("note_to_pharmacist", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_favorites",
                        to="users.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["label", "drug_name", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="prescriptionfavorite",
            index=models.Index(fields=["owner"], name="appointment_owner_i_c629db_idx"),
        ),
    ]
