# Generated by Django 4.2 on 2026-10-09 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0039_registration_resident_provider"),
        ("appointments", "0056_prescription_favorites_renewals"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "code_system",
                    models.CharField(blank=True, default="icd10cm", max_length=10),
                ),
                ("code", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("chronic", "Chronic"),
                            ("resolved", "Resolved"),
                            ("entered_in_error", "Entered in error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("onset_date", models.DateField(blank=True, null=True)),
                ("resolved_date", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_entries",
                        to="users.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="problem_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["description", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="problemlistentry",
            index=models.Index(
                fields=["organization", "patient", "status"],
                name="appointment_organiz_4fb7f0_idx",
            ),
        ),
    ]
