# Generated by Django 4.2 on 2026-09-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profession',
            field=models.CharField(help_text="Free-text role, e.g. Nurse, Physician, CNA, Tech -- whatever the org's roster uses.", max_length=100),
        ),
    ]
