# Generated by Django 4.2 on 2026-09-28 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_userrightoverride'),
        ('staffing', '0002_alter_staff_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='reminders_enabled',
            field=models.BooleanField(default=True, help_text="Master on/off switch for this staff member's automatic SMS/email shift reminders (sent ~3 hours before a shift starts). Toggled from the Messaging column on the Roster tab."),
        ),
        migrations.AddField(
            model_name='staffshift',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the ~3-hours-before-shift SMS/email reminder was sent to this staff member. Null means not sent yet; used to make the hourly reminder job idempotent.', null=True),
        ),
        migrations.CreateModel(
            name='ShiftCoverageRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('day', 'Day'), ('evening', 'Evening'), ('night', 'Night'), ('custom', 'Custom')], default='day', max_length=20)),
                ('days_of_week', models.JSONField(default=list, help_text="List of day codes this coverage requirement applies on, e.g. ['mon','wed','fri'].")),
                ('min_staff_required', models.PositiveIntegerField(default=1, help_text='Minimum number of distinct staff that must be assigned/covering for this shift type on an applicable date.')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for an ongoing/open-ended requirement.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffing_coverage_requirements', to='users.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('staff_assigned_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_sent', to='staffing.shiftcoveragerequirement')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('requirement', 'date')},
            },
        ),
    ]
